#!/usr/bin/perl -w
$|++;
use strict;

# This program scrapes the entries under "Viering/Herdenkingen" on the
# Wikipedia page that is given by the first argument. Use the script
# getinfo.sh to scrape multiple pages.

my $flag = 0;
my $firstprint = 1;

for (`w3m nl.wikipedia.org/wiki/$ARGV[0]`)
{ 
  if ($flag)
  {
    chomp $_;
    $flag = 0 if $_ =~ /bewerken/;
    if ($_ =~ / • (.*)/)
    {
      if ($firstprint)
      {
        print "$1";
        $firstprint = 0;
      }
      else
      {
        print "\\\\\n$1";
      }
    }
  }
    
  if ($_ =~ ".*bewerken.*Viering.herdenking")
  {
    $flag = 1;
  }
}  

print "\n";
